### ISSUE TITLE
Compiling

### ISSUE THREAD

**Issue by neilcook** [Bosma/Scheduler#1]
I cannot get this to compile with either clang or g++, e.g.

Projects/Scheduler/Cron.h:13:41: error: no viable conversion from 'time_point<[...],
      duration<[...], ratio<[...], __static_lcm<ratio<1, 1000000>::den, ratio<1, 1000000000>::den>::value aka
      1000000000>>>' to 'const time_point<[...], duration<[...], ratio<[...], 1000000>>>'
    auto tm_adjusted = Clock::to_time_t(tp + time);

Also, do you have any plans to use make this work with C++11?

**Comment by Bosma** [comment]
Let me know if it's working now. I didn't come across this issue because all the systems I tested on had nanosecond precision system_clocks. 

I also removed the C++14 requirement (since it was trivial to do).

**Comment by neilcook** [comment]
Thanks for responding so quickly - I'll try it out and let you know

**Comment by neilcook** [comment]
That works great, thanks! 

I really like this library, and I already use ctpl for my own thread pooling, so it fits right it with my projects. Great work!
