### ISSUE TITLE
'now' method

### ISSUE THREAD

**Issue by asmyasnikov** [Bosma/Scheduler#5]
Hi!
Can you add 'now' method for executing some code inside Bosma::Scheduller workers thread pool like this:
            template<typename _Callable, typename... _Args> void now(_Callable &&f, _Args &&... args) {
                in(std::chrono::nanoseconds(0), std::forward<_Callable>(f), std::forward<_Args>(args)...);
            }
This feature in my project help me for free main thread execution using Bosma::Scheduller features.
To your notice =)

**Comment by asmyasnikov** [comment]
I create pull request for this feature
https://github.com/Bosma/Scheduler/pull/6

**Comment by Bosma** [comment]
Thanks for the suggestion, but I would like to keep the library simple, so you should instead call `s.in(0s, []() { std::cout << "now" << std::endl; });` directly or write your own wrapper.
