### ISSUE TITLE
Unsupported cron string leads to unhandled exception

### ISSUE THREAD

**Issue by Tickwick** [Bosma/Scheduler#9]
`cronScheduler.cron("*/5 * * * *", []() { Foo(); });`

This leads to an "invalid stoi argument" exception, at least on MSVC 15.6. I think it's the responsability of the library to gracefully handle incorrect or unsupported arguments for its functions.

**Comment by Bosma** [comment]
I didn't take into account that type of malformed cron string, thanks for reporting.

It continues to throw an exception, however it is a more descriptive BadCronExpression exception that contains a message with the error.

**Comment by Tickwick** [comment]
Any plans on supporting that type of cron string in the future?

**Comment by Bosma** [comment]
Sorry, I didn't realize that were more complicated expressions. I added in the latest commit an alternative cron function ccron that uses a different (included) [library](https://github.com/staticlibs/ccronexpr). This should work for you, let me know.

**Comment by Tickwick** [comment]
Thanks for the support, first a couple of minor issues:
1. [Wrong include path](https://github.com/Bosma/Scheduler/commit/797b6526863145da2290a1a322fc2949de1077c5#diff-f737f1a8507ce09732379dc5eb2edecbR8)
2. [Here](https://github.com/Bosma/Scheduler/commit/4f950e91b63b11bdb342e80b663349ed7db42a1b#diff-57c7abf2a0e26a642915a9b0d568c5d9R35) and on the catch below that, there's an unused declared `e` var that throws warnings on compile.

Second, as it stands now, due to the C lib include, this library is not header only anymore, any usage of `ccron` requires compilation of `ccronexpr.c`.

**Comment by Bosma** [comment]
Yes you're right, I reset the last commit and moved it to a branch. I'd prefer to keep it header-only. If you want the functionality offered use the ccronexpr branch. The include path was correct given the include_directories entry in the cmakelists. I dropped the `e`. Thanks.
